version: "3.8"

networks:
    marketplace_app:
        driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        depends_on:
            - php
            - db
        ports:
            - "8084:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - marketplace_app

    db:
        image: mysql:8.0.20
        container_name: db
        restart: unless-stopped
        tty: true
        networks:
            - marketplace_app
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            SERVICE_TAGS: dev
            SERVICE_NAME: "${DB_CONNECTION}"

    php:
        container_name: php_marketplace_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - marketplace_app

    npm:
        image: node:latest
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["npm", "--no-bin-links"]
        command: bash -c "npm install && npm run dev"
        networks:
            - marketplace_app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        depends_on:
            - db
        ports:
            - "8085:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        networks:
            - marketplace_app
